version: '3'

services:
  app:
    build:
      context: ./
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      - 3000:3000
    depends_on: 
    - kafka
    - connect
    - postgres
